/*
 * Created on 13 Jan 2016 ( Time 16:21:05 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.gkd.springwebgkd.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class MwhsGudang implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 3 )
    private String kode;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 200 )
    private String namaGudang;

    @Size( max = 6 )
    private String kdSupp;

    @Size( max = 200 )
    private String keterangan;
    
    @Size( max = 1 )
    private String     flagAktif   ;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setKode( String kode ) {
        this.kode = kode ;
    }

    public String getKode() {
        return this.kode;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setNamaGudang( String namaGudang ) {
        this.namaGudang = namaGudang;
    }
    public String getNamaGudang() {
        return this.namaGudang;
    }

    public void setKdSupp( String kdSupp ) {
        this.kdSupp = kdSupp;
    }
    public String getKdSupp() {
        return this.kdSupp;
    }

    public void setKeterangan( String keterangan ) {
        this.keterangan = keterangan;
    }
    public String getKeterangan() {
        return this.keterangan;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(kode);
        sb.append("|");
        sb.append(namaGudang);
        sb.append("|");
        sb.append(kdSupp);
        sb.append("|");
        sb.append(keterangan);
        return sb.toString(); 
    } 


}
