/*
 * Created on 26 Jan 2016 ( Time 08:40:59 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.gkd.springwebgkd.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.math.BigDecimal;
import java.util.Date;

public class WhsSjScan implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private BigDecimal kdTrx;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 30 )
    private String noBarcode;

    @NotNull
    @Size( min = 1, max = 4 )
    private String tahun;

    @NotNull
    @Size( min = 1, max = 2 )
    private String bulan;


    private Date tglTrx;


    private BigDecimal qtyScan;

    @Size( max = 4 )
    private String kdGudang;

    @Size( max = 1 )
    private String stTarik;


    private Date createdate;

    @Size( max = 10 )
    private String createby;


    private Date modidate;

    @Size( max = 10 )
    private String modiby;

    @Size( max = 100 )
    private String keterangan;

    @Size( max = 20 )
    private String noSpag;

    @Size( max = 1 )
    private String stDel;

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setKdTrx( BigDecimal kdTrx ) {
        this.kdTrx = kdTrx ;
    }

    public BigDecimal getKdTrx() {
        return this.kdTrx;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setNoBarcode( String noBarcode ) {
        this.noBarcode = noBarcode;
    }
    public String getNoBarcode() {
        return this.noBarcode;
    }

    public void setTahun( String tahun ) {
        this.tahun = tahun;
    }
    public String getTahun() {
        return this.tahun;
    }

    public void setBulan( String bulan ) {
        this.bulan = bulan;
    }
    public String getBulan() {
        return this.bulan;
    }

    public void setTglTrx( Date tglTrx ) {
        this.tglTrx = tglTrx;
    }
    public Date getTglTrx() {
        return this.tglTrx;
    }

    public void setQtyScan( BigDecimal qtyScan ) {
        this.qtyScan = qtyScan;
    }
    public BigDecimal getQtyScan() {
        return this.qtyScan;
    }

    public void setKdGudang( String kdGudang ) {
        this.kdGudang = kdGudang;
    }
    public String getKdGudang() {
        return this.kdGudang;
    }

    public void setStTarik( String stTarik ) {
        this.stTarik = stTarik;
    }
    public String getStTarik() {
        return this.stTarik;
    }

    public void setCreatedate( Date createdate ) {
        this.createdate = createdate;
    }
    public Date getCreatedate() {
        return this.createdate;
    }

    public void setCreateby( String createby ) {
        this.createby = createby;
    }
    public String getCreateby() {
        return this.createby;
    }

    public void setModidate( Date modidate ) {
        this.modidate = modidate;
    }
    public Date getModidate() {
        return this.modidate;
    }

    public void setModiby( String modiby ) {
        this.modiby = modiby;
    }
    public String getModiby() {
        return this.modiby;
    }

    public void setKeterangan( String keterangan ) {
        this.keterangan = keterangan;
    }
    public String getKeterangan() {
        return this.keterangan;
    }

    public String getStDel() {
		return stDel;
	}

	public void setStDel(String stDel) {
		this.stDel = stDel;
	}

	public void setNoSpag( String noSpag ) {
        this.noSpag = noSpag;
    }
    public String getNoSpag() {
        return this.noSpag;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(kdTrx);
        sb.append("|");
        sb.append(noBarcode);
        sb.append("|");
        sb.append(tahun);
        sb.append("|");
        sb.append(bulan);
        sb.append("|");
        sb.append(tglTrx);
        sb.append("|");
        sb.append(qtyScan);
        sb.append("|");
        sb.append(kdGudang);
        sb.append("|");
        sb.append(stTarik);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(createby);
        sb.append("|");
        sb.append(modidate);
        sb.append("|");
        sb.append(modiby);
        sb.append("|");
        sb.append(keterangan);
        sb.append("|");
        sb.append(noSpag);
        return sb.toString(); 
    } 


}
