/*
 * Created on 23 Des 2015 ( Time 11:12:13 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.gkd.springwebgkd.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import org.hibernate.annotations.Formula;

import java.math.BigDecimal;
import java.util.Date;

public class WhsSupplyScan implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 20 )
    private BigDecimal kdTrx;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 30 )
    private String noBarcode;

    @NotNull
    @Size( min = 1, max = 4 )
    private String tahun;

    @NotNull
    @Size( min = 1, max = 2 )
    private String bulan;


    private Date tanggalTrx;


    private BigDecimal qtyBpb;

    @Size( max = 50 )
    private String locScan;

    @Size( max = 3 )
    private String stApprove;

    @Size( max = 20 )
    private String kdLine;

    @Size( max = 20 )
    private String noDps;

    @Size( max = 6 )
    private String picProd;

    @Size( max = 200 )
    private String keterangan;


    private Date createdate;

    @Size( max = 10 )
    private String createby;


    private Date modidate;

    @Size( max = 10 )
    private String modiby;

    @Size( max = 3 )
    private String stInout;

    @Size( max = 20 )
    private String kdMesin;
    
    @Size( max = 3 )
    private String kdGudang;
    
    @Size( max = 21 )
    private String noBpb;
    
    @Size( max = 50 )
    private String kdBrg;
    
    private BigDecimal qtySupply;
    
    private BigDecimal qtyRetur;
//
//    @Size( max = 200 )
//    private String nmBrg;

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setKdTrx( BigDecimal kdTrx ) {
        this.kdTrx = kdTrx ;
    }

    public BigDecimal getKdTrx() {
        return this.kdTrx;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setNoBarcode( String noBarcode ) {
        this.noBarcode = noBarcode;
    }
    public String getNoBarcode() {
        return this.noBarcode;
    }

    public void setTahun( String tahun ) {
        this.tahun = tahun;
    }
    public String getTahun() {
        return this.tahun;
    }

    public void setBulan( String bulan ) {
        this.bulan = bulan;
    }
    public String getBulan() {
        return this.bulan;
    }

    public void setTanggalTrx( Date tanggalTrx ) {
        this.tanggalTrx = tanggalTrx;
    }
    public Date getTanggalTrx() {
        return this.tanggalTrx;
    }

    public void setLocScan( String locScan ) {
        this.locScan = locScan;
    }
    public String getLocScan() {
        return this.locScan;
    }

    public void setStApprove( String stApprove ) {
        this.stApprove = stApprove;
    }
    public String getStApprove() {
        return this.stApprove;
    }

    public void setKdLine( String kdLine ) {
        this.kdLine = kdLine;
    }
    public String getKdLine() {
        return this.kdLine;
    }

    public void setNoDps( String noDps ) {
        this.noDps = noDps;
    }
    public String getNoDps() {
        return this.noDps;
    }

    public void setPicProd( String picProd ) {
        this.picProd = picProd;
    }
    public String getPicProd() {
        return this.picProd;
    }

    public void setKeterangan( String keterangan ) {
        this.keterangan = keterangan;
    }
    public String getKeterangan() {
        return this.keterangan;
    }

    public void setCreatedate( Date createdate ) {
        this.createdate = createdate;
    }
    public Date getCreatedate() {
        return this.createdate;
    }

    public void setCreateby( String createby ) {
        this.createby = createby;
    }
    public String getCreateby() {
        return this.createby;
    }

    public void setModidate( Date modidate ) {
        this.modidate = modidate;
    }
    public Date getModidate() {
        return this.modidate;
    }

    public void setModiby( String modiby ) {
        this.modiby = modiby;
    }
    public String getModiby() {
        return this.modiby;
    }

    public void setStInout( String stInout ) {
        this.stInout = stInout;
    }
    public String getStInout() {
        return this.stInout;
    }

    public void setKdMesin( String kdMesin ) {
        this.kdMesin = kdMesin;
    }
    public String getKdMesin() {
        return this.kdMesin;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
  public String getKdBrg() {
		return kdBrg;
	}

	public void setKdBrg(String kdBrg) {
		this.kdBrg = kdBrg;
	}
//
//	public String getNmBrg() {
//		return nmBrg;
//	}
//
//	public void setNmBrg(String nmBrg) {
//		this.nmBrg = nmBrg;
//	}

		public BigDecimal getQtyBpb() {
		return qtyBpb;
	}

	public void setQtyBpb(BigDecimal qtyBpb) {
		this.qtyBpb = qtyBpb;
	}

	public String getKdGudang() {
		return kdGudang;
	}

	public void setKdGudang(String kdGudang) {
		this.kdGudang = kdGudang;
	}

	public String getNoBpb() {
		return noBpb;
	}

	public void setNoBpb(String noBpb) {
		this.noBpb = noBpb;
	}

	public BigDecimal getQtySupply() {
		return qtySupply;
	}

	public void setQtySupply(BigDecimal qtySupply) {
		this.qtySupply = qtySupply;
	}

	public BigDecimal getQtyRetur() {
		return qtyRetur;
	}

	public void setQtyRetur(BigDecimal qtyRetur) {
		this.qtyRetur = qtyRetur;
	}

	public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(noBarcode);
        sb.append("|");
        sb.append(tahun);
        sb.append("|");
        sb.append(bulan);
        sb.append("|");
        sb.append(tanggalTrx);
        sb.append("|");
        sb.append(qtyBpb);
        sb.append("|");
        sb.append(locScan);
        sb.append("|");
        sb.append(stApprove);
        sb.append("|");
        sb.append(kdLine);
        sb.append("|");
        sb.append(noDps);
        sb.append("|");
        sb.append(picProd);
        sb.append("|");
        sb.append(keterangan);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(createby);
        sb.append("|");
        sb.append(modidate);
        sb.append("|");
        sb.append(modiby);
        sb.append("|");
        sb.append(kdTrx);
        sb.append("|");
        sb.append(stInout);
        sb.append("|");
        sb.append(kdMesin);
        return sb.toString(); 
    } 


}
