/*
 * Created on 13 Jan 2016 ( Time 16:20:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.gkd.springwebgkd.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "MWHS_GUDANG"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="MWHS_GUDANG", schema="USRGKDMFG" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="MwhsGudangEntity.countAll", query="SELECT COUNT(x) FROM MwhsGudangEntity x" )
} )
public class MwhsGudangEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="KODE", nullable=false, length=3)
    private String     kode         ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="NAMA_GUDANG", length=200)
    private String     namaGudang   ;

    @Column(name="KD_SUPP", length=6)
    private String     kdSupp       ;

    @Column(name="KETERANGAN", length=200)
    private String     keterangan   ;
    
    @Column(name="FLAG_AKTIF", length=1)
    private String     flagAktif   ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public MwhsGudangEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setKode( String kode ) {
        this.kode = kode ;
    }
    public String getKode() {
        return this.kode;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NAMA_GUDANG ( VARCHAR2 ) 
    public void setNamaGudang( String namaGudang ) {
        this.namaGudang = namaGudang;
    }
    public String getNamaGudang() {
        return this.namaGudang;
    }

    //--- DATABASE MAPPING : KD_SUPP ( VARCHAR2 ) 
    public void setKdSupp( String kdSupp ) {
        this.kdSupp = kdSupp;
    }
    public String getKdSupp() {
        return this.kdSupp;
    }

    //--- DATABASE MAPPING : KETERANGAN ( VARCHAR2 ) 
    public void setKeterangan( String keterangan ) {
        this.keterangan = keterangan;
    }
    public String getKeterangan() {
        return this.keterangan;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    public String getFlagAktif() {
		return flagAktif;
	}

	public void setFlagAktif(String flagAktif) {
		this.flagAktif = flagAktif;
	}

	//----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(kode);
        sb.append("]:"); 
        sb.append(namaGudang);
        sb.append("|");
        sb.append(kdSupp);
        sb.append("|");
        sb.append(keterangan);
        return sb.toString(); 
    } 

}
