/*
 * Created on 4 Mar 2016 ( Time 09:42:25 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.gkd.springwebgkd.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "WHS_SUPPLY_SCANX"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="WHS_SUPPLY_SCANX", schema="USRGKDMFG" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="WhsSupplyScanxEntity.countAll", query="SELECT COUNT(x) FROM WhsSupplyScanxEntity x" )
} )
public class WhsSupplyScanxEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="KD_TRX", nullable=false)
    private BigDecimal kdTrx        ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="NO_BARCODE", nullable=false, length=30)
    private String     noBarcode    ;

    @Column(name="TAHUN", nullable=false, length=4)
    private String     tahun        ;

    @Column(name="BULAN", nullable=false, length=2)
    private String     bulan        ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TANGGAL_TRX")
    private Date       tanggalTrx   ;

    @Column(name="QTY_BPB")
    private BigDecimal qtyBpb       ;

    @Column(name="LOC_SCAN", length=50)
    private String     locScan      ;

    @Column(name="ST_APPROVE", length=3)
    private String     stApprove    ;

    @Column(name="KD_LINE", length=20)
    private String     kdLine       ;

    @Column(name="NO_DPS", length=20)
    private String     noDps        ;

    @Column(name="PIC_PROD", length=6)
    private String     picProd      ;

    @Column(name="KETERANGAN", length=200)
    private String     keterangan   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDATE")
    private Date       createdate   ;

    @Column(name="CREATEBY", length=10)
    private String     createby     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIDATE")
    private Date       modidate     ;

    @Column(name="MODIBY", length=10)
    private String     modiby       ;

    @Column(name="KD_MESIN", length=20)
    private String     kdMesin      ;

    @Column(name="KD_GUDANG", length=3)
    private String     kdGudang     ;

    @Column(name="NO_BPB", length=21)
    private String     noBpb        ;

    @Column(name="QTY_RETUR")
    private BigDecimal qtyRetur     ;

    @Column(name="QTY_SUPPLY")
    private BigDecimal qtySupply    ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public WhsSupplyScanxEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setKdTrx( BigDecimal kdTrx ) {
        this.kdTrx = kdTrx ;
    }
    public BigDecimal getKdTrx() {
        return this.kdTrx;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NO_BARCODE ( VARCHAR2 ) 
    public void setNoBarcode( String noBarcode ) {
        this.noBarcode = noBarcode;
    }
    public String getNoBarcode() {
        return this.noBarcode;
    }

    //--- DATABASE MAPPING : TAHUN ( VARCHAR2 ) 
    public void setTahun( String tahun ) {
        this.tahun = tahun;
    }
    public String getTahun() {
        return this.tahun;
    }

    //--- DATABASE MAPPING : BULAN ( VARCHAR2 ) 
    public void setBulan( String bulan ) {
        this.bulan = bulan;
    }
    public String getBulan() {
        return this.bulan;
    }

    //--- DATABASE MAPPING : TANGGAL_TRX ( DATE ) 
    public void setTanggalTrx( Date tanggalTrx ) {
        this.tanggalTrx = tanggalTrx;
    }
    public Date getTanggalTrx() {
        return this.tanggalTrx;
    }

    //--- DATABASE MAPPING : QTY_BPB ( NUMBER ) 
    public void setQtyBpb( BigDecimal qtyBpb ) {
        this.qtyBpb = qtyBpb;
    }
    public BigDecimal getQtyBpb() {
        return this.qtyBpb;
    }

    //--- DATABASE MAPPING : LOC_SCAN ( VARCHAR2 ) 
    public void setLocScan( String locScan ) {
        this.locScan = locScan;
    }
    public String getLocScan() {
        return this.locScan;
    }

    //--- DATABASE MAPPING : ST_APPROVE ( VARCHAR2 ) 
    public void setStApprove( String stApprove ) {
        this.stApprove = stApprove;
    }
    public String getStApprove() {
        return this.stApprove;
    }

    //--- DATABASE MAPPING : KD_LINE ( VARCHAR2 ) 
    public void setKdLine( String kdLine ) {
        this.kdLine = kdLine;
    }
    public String getKdLine() {
        return this.kdLine;
    }

    //--- DATABASE MAPPING : NO_DPS ( VARCHAR2 ) 
    public void setNoDps( String noDps ) {
        this.noDps = noDps;
    }
    public String getNoDps() {
        return this.noDps;
    }

    //--- DATABASE MAPPING : PIC_PROD ( VARCHAR2 ) 
    public void setPicProd( String picProd ) {
        this.picProd = picProd;
    }
    public String getPicProd() {
        return this.picProd;
    }

    //--- DATABASE MAPPING : KETERANGAN ( VARCHAR2 ) 
    public void setKeterangan( String keterangan ) {
        this.keterangan = keterangan;
    }
    public String getKeterangan() {
        return this.keterangan;
    }

    //--- DATABASE MAPPING : CREATEDATE ( DATE ) 
    public void setCreatedate( Date createdate ) {
        this.createdate = createdate;
    }
    public Date getCreatedate() {
        return this.createdate;
    }

    //--- DATABASE MAPPING : CREATEBY ( VARCHAR2 ) 
    public void setCreateby( String createby ) {
        this.createby = createby;
    }
    public String getCreateby() {
        return this.createby;
    }

    //--- DATABASE MAPPING : MODIDATE ( DATE ) 
    public void setModidate( Date modidate ) {
        this.modidate = modidate;
    }
    public Date getModidate() {
        return this.modidate;
    }

    //--- DATABASE MAPPING : MODIBY ( VARCHAR2 ) 
    public void setModiby( String modiby ) {
        this.modiby = modiby;
    }
    public String getModiby() {
        return this.modiby;
    }

    //--- DATABASE MAPPING : KD_MESIN ( VARCHAR2 ) 
    public void setKdMesin( String kdMesin ) {
        this.kdMesin = kdMesin;
    }
    public String getKdMesin() {
        return this.kdMesin;
    }

    //--- DATABASE MAPPING : KD_GUDANG ( VARCHAR2 ) 
    public void setKdGudang( String kdGudang ) {
        this.kdGudang = kdGudang;
    }
    public String getKdGudang() {
        return this.kdGudang;
    }

    //--- DATABASE MAPPING : NO_BPB ( VARCHAR2 ) 
    public void setNoBpb( String noBpb ) {
        this.noBpb = noBpb;
    }
    public String getNoBpb() {
        return this.noBpb;
    }

    //--- DATABASE MAPPING : QTY_RETUR ( NUMBER ) 
    public void setQtyRetur( BigDecimal qtyRetur ) {
        this.qtyRetur = qtyRetur;
    }
    public BigDecimal getQtyRetur() {
        return this.qtyRetur;
    }

    //--- DATABASE MAPPING : QTY_SUPPLY ( NUMBER ) 
    public void setQtySupply( BigDecimal qtySupply ) {
        this.qtySupply = qtySupply;
    }
    public BigDecimal getQtySupply() {
        return this.qtySupply;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(kdTrx);
        sb.append("]:"); 
        sb.append(noBarcode);
        sb.append("|");
        sb.append(tahun);
        sb.append("|");
        sb.append(bulan);
        sb.append("|");
        sb.append(tanggalTrx);
        sb.append("|");
        sb.append(qtyBpb);
        sb.append("|");
        sb.append(locScan);
        sb.append("|");
        sb.append(stApprove);
        sb.append("|");
        sb.append(kdLine);
        sb.append("|");
        sb.append(noDps);
        sb.append("|");
        sb.append(picProd);
        sb.append("|");
        sb.append(keterangan);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(createby);
        sb.append("|");
        sb.append(modidate);
        sb.append("|");
        sb.append(modiby);
        sb.append("|");
        sb.append(kdMesin);
        sb.append("|");
        sb.append(kdGudang);
        sb.append("|");
        sb.append(noBpb);
        sb.append("|");
        sb.append(qtyRetur);
        sb.append("|");
        sb.append(qtySupply);
        return sb.toString(); 
    } 

}
