/*
 * Created on 22 Des 2015 ( Time 13:44:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.gkd.springwebgkd.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "WHS_SUPPLY_LOG"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="WHS_SUPPLY_LOG", schema="USRGKDMFG" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="WhsSupplyLogEntity.countAll", query="SELECT COUNT(x) FROM WhsSupplyLogEntity x" )
} )
public class WhsSupplyLogEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="NO_ID", nullable=false)
    private BigDecimal noId         ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="KODE_BARCODE", length=40)
    private String     kodeBarcode  ;

    @Column(name="KD_BRG", length=20)
    private String     kdBrg        ;

    @Column(name="QTY")
    private BigDecimal qty          ;

    @Temporal(TemporalType.DATE)
    @Column(name="TGL_TRX")
    private Date       tglTrx       ;

    @Column(name="STATUS", length=20)
    private String     status       ;

    @Column(name="LOKASI", length=20)
    private String     lokasi       ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public WhsSupplyLogEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setNoId( BigDecimal noId ) {
        this.noId = noId ;
    }
    public BigDecimal getNoId() {
        return this.noId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : KODE_BARCODE ( VARCHAR2 ) 
    public void setKodeBarcode( String kodeBarcode ) {
        this.kodeBarcode = kodeBarcode;
    }
    public String getKodeBarcode() {
        return this.kodeBarcode;
    }

    //--- DATABASE MAPPING : KD_BRG ( VARCHAR2 ) 
    public void setKdBrg( String kdBrg ) {
        this.kdBrg = kdBrg;
    }
    public String getKdBrg() {
        return this.kdBrg;
    }

    //--- DATABASE MAPPING : QTY ( NUMBER ) 
    public void setQty( BigDecimal qty ) {
        this.qty = qty;
    }
    public BigDecimal getQty() {
        return this.qty;
    }

    //--- DATABASE MAPPING : TGL_TRX ( DATE ) 
    public void setTglTrx( Date tglTrx ) {
        this.tglTrx = tglTrx;
    }
    public Date getTglTrx() {
        return this.tglTrx;
    }

    //--- DATABASE MAPPING : STATUS ( VARCHAR2 ) 
    public void setStatus( String status ) {
        this.status = status;
    }
    public String getStatus() {
        return this.status;
    }

    //--- DATABASE MAPPING : LOKASI ( VARCHAR2 ) 
    public void setLokasi( String lokasi ) {
        this.lokasi = lokasi;
    }
    public String getLokasi() {
        return this.lokasi;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(noId);
        sb.append("]:"); 
        sb.append(kodeBarcode);
        sb.append("|");
        sb.append(kdBrg);
        sb.append("|");
        sb.append(qty);
        sb.append("|");
        sb.append(tglTrx);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(lokasi);
        return sb.toString(); 
    } 

}
