/*
 * Created on 22 Des 2015 ( Time 13:48:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.gkd.springwebgkd.repo;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import org.gkd.springwebgkd.bean.jpa.MwhsGudangEntity;
import org.gkd.springwebgkd.common.repo.AbstractRepository;
import org.springframework.stereotype.Component;

/**
 * JPA implementation for basic persistence operations ( entity "WhsSupplyScan"
 * )
 * 
 * @author Telosys Tools Generator
 *
 */
@Component
public class MwhsGudangRepository extends AbstractRepository<MwhsGudangEntity, String> {

	@PersistenceContext
	private EntityManager entityManager;

	/**
	 * Constructor
	 */
	public MwhsGudangRepository() {
		super(MwhsGudangEntity.class);
	}

	@Override
	protected EntityManager getEntityManager() {
		return this.entityManager;
	}

	@Override
	public boolean delete(MwhsGudangEntity entity, String id) {
		if (entity != null) {
			return super.delete(entity, entity.getKode());
		}
		return false;
	}

	
	public long countAll() throws PersistenceException {
		try {
			Query query = entityManager.createNamedQuery("MwhsGudangEntity.countAll");
			return (long) query.getSingleResult();
		} finally {
			entityManager.close();
		}
	}

}
