/*
 * Created on 22 Des 2015 ( Time 13:48:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.gkd.springwebgkd.repo;

import java.math.BigDecimal;
import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.NoResultException;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import org.gkd.springwebgkd.bean.jpa.WhsSupplyScanxEntity;
import org.gkd.springwebgkd.common.repo.AbstractRepository;
import org.springframework.stereotype.Component;

/**
 * JPA implementation for basic persistence operations ( entity "WhsSupplyScan"
 * )
 * 
 * @author Telosys Tools Generator
 *
 */
@Component
public class WhsSupplyScanxRepository extends AbstractRepository<WhsSupplyScanxEntity, BigDecimal> {

	@PersistenceContext
	private EntityManager entityManager;

	/**
	 * Constructor
	 */
	public WhsSupplyScanxRepository() {
		super(WhsSupplyScanxEntity.class);
	}

	@Override
	protected EntityManager getEntityManager() {
		return this.entityManager;
	}

	@Override
	public boolean delete(WhsSupplyScanxEntity entity, BigDecimal id) {
		if (entity != null) {
			return super.delete(entity, entity.getKdTrx());
		}
		return false;
	}

	
	public long countAll() throws PersistenceException {
		try {
			Query query = entityManager.createNamedQuery("WhsSupplyScanxEntity.countAll");
			return (long) query.getSingleResult();
		} finally {
			entityManager.close();
		}
	}
	
	public BigDecimal findMaxKdTrx() throws PersistenceException {
		try {
			String sql = "SELECT NVL(MAX(KD_TRX),0) + 1 FROM WHS_SUPPLY_SCANX";
			Query query = entityManager.createNativeQuery(sql);
			return (BigDecimal) query.getSingleResult();
		} finally {
			entityManager.close();
		}
	}
	
	
	public String openPeriodeBpb() throws PersistenceException {
		try {
			String sql = "SELECT FOPEN_PERIODE_BPB1('N') FROM DUAL";
			Query query = entityManager.createNativeQuery(sql);
			return (String) query.getSingleResult();
		} finally {
			entityManager.close();
		}
	}
	
	@SuppressWarnings("unchecked")
	public List<WhsSupplyScanxEntity> findListSupplyHarian(String kdGudang) throws PersistenceException {
		try {
			String sql = "SELECT * FROM (SELECT p.* FROM WHS_SUPPLY_SCANX p "
					+ "WHERE TO_CHAR(TANGGAL_TRX,'YYYYMMDD') = TO_CHAR(SYSDATE,'YYYYMMDD') "
					+ "AND p.KD_GUDANG = '"+kdGudang+"' AND p.NO_BPB IS NULL ORDER BY p.TANGGAL_TRX DESC) WHERE ROWNUM <= 10";
			Query query = entityManager.createNativeQuery(sql, WhsSupplyScanxEntity.class);
			
			return query.getResultList();
		} finally {
			entityManager.close();
		}
	}
	
}
