/*
 * Created on 22 Des 2015 ( Time 13:44:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.gkd.springwebgkd.repo;

import java.math.BigDecimal;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import org.gkd.springwebgkd.bean.jpa.WebgkdUsersecEntity;
import org.gkd.springwebgkd.bean.jpa.WhsSupplyLogEntity;
import org.gkd.springwebgkd.common.repo.AbstractRepository;

/**
 * JPA implementation for basic persistence operations ( entity "WhsSupplyLog" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class WhsSupplyLogRepository extends AbstractRepository<WhsSupplyLogEntity, BigDecimal> {

	@PersistenceContext
	private EntityManager entityManager;

	/**
	 * Constructor
	 */
	public WhsSupplyLogRepository() {
		super(WhsSupplyLogEntity.class);
	}

	@Override
	protected EntityManager getEntityManager() {
		return this.entityManager;
	}

	@Override
	public boolean delete(WhsSupplyLogEntity entity, BigDecimal id) {
		if (entity != null) {
			return super.delete(entity, entity.getNoId());
		}
		return false;
	}

	public long countAll() throws PersistenceException {
		try {
			Query query = entityManager.createNamedQuery("WhsSupplyLogEntity.countAll");
			return (long) query.getSingleResult();
		} finally {
			entityManager.close();
		}
	}

}
