/*
 * Created on 13 Jan 2016 ( Time 16:20:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.gkd.springwebgkd.service.mapper;

import org.gkd.springwebgkd.bean.MwhsGudang;
import org.gkd.springwebgkd.bean.jpa.MwhsGudangEntity;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class MwhsGudangServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public MwhsGudangServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'MwhsGudangEntity' to 'MwhsGudang'
	 * @param mwhsGudangEntity
	 */
	public MwhsGudang mapMwhsGudangEntityToMwhsGudang(MwhsGudangEntity mwhsGudangEntity) {
		if(mwhsGudangEntity == null) {
			return null;
		}

		//--- Generic mapping 
		MwhsGudang mwhsGudang = map(mwhsGudangEntity, MwhsGudang.class);

		return mwhsGudang;
	}
	
	/**
	 * Mapping from 'MwhsGudang' to 'MwhsGudangEntity'
	 * @param mwhsGudang
	 * @param mwhsGudangEntity
	 */
	public void mapMwhsGudangToMwhsGudangEntity(MwhsGudang mwhsGudang, MwhsGudangEntity mwhsGudangEntity) {
		if(mwhsGudang == null) {
			return;
		}

		//--- Generic mapping 
		map(mwhsGudang, mwhsGudangEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}