/*
 * Created on 4 Jan 2016 ( Time 13:49:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.gkd.springwebgkd.service.mapper;

import org.gkd.springwebgkd.bean.TagLpb;
import org.gkd.springwebgkd.bean.jpa.TagLpbEntity;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class TagLpbServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public TagLpbServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'TagLpbEntity' to 'TagLpb'
	 * @param tagLpbEntity
	 */
	public TagLpb mapTagLpbEntityToTagLpb(TagLpbEntity tagLpbEntity) {
		if(tagLpbEntity == null) {
			return null;
		}

		//--- Generic mapping 
		TagLpb tagLpb = map(tagLpbEntity, TagLpb.class);

		return tagLpb;
	}
	
	/**
	 * Mapping from 'TagLpb' to 'TagLpbEntity'
	 * @param tagLpb
	 * @param tagLpbEntity
	 */
	public void mapTagLpbToTagLpbEntity(TagLpb tagLpb, TagLpbEntity tagLpbEntity) {
		if(tagLpb == null) {
			return;
		}

		//--- Generic mapping 
		map(tagLpb, tagLpbEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}