/*
 * Created on 23 Des 2015 ( Time 11:11:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.gkd.springwebgkd.service.mapper;

import org.gkd.springwebgkd.bean.WhsSupplyLog;
import org.gkd.springwebgkd.bean.jpa.WhsSupplyLogEntity;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class WhsSupplyLogServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */	
	public WhsSupplyLogServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'WhsSupplyLogEntity' to 'WhsSupplyLog'
	 * @param whsSupplyLogEntity
	 */
	public WhsSupplyLog mapWhsSupplyLogEntityToWhsSupplyLog(WhsSupplyLogEntity whsSupplyLogEntity) {
		if(whsSupplyLogEntity == null) {
			return null;
		}

		//--- Generic mapping 
		WhsSupplyLog whsSupplyLog = map(whsSupplyLogEntity, WhsSupplyLog.class);

		return whsSupplyLog;
	}
	
	/**
	 * Mapping from 'WhsSupplyLog' to 'WhsSupplyLogEntity'
	 * @param whsSupplyLog
	 * @param whsSupplyLogEntity
	 */
	public void mapWhsSupplyLogToWhsSupplyLogEntity(WhsSupplyLog whsSupplyLog, WhsSupplyLogEntity whsSupplyLogEntity) {
		if(whsSupplyLog == null) {
			return;
		}

		//--- Generic mapping 
		map(whsSupplyLog, whsSupplyLogEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}