/*
 * Created on 23 Des 2015 ( Time 11:11:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.gkd.springwebgkd.service.mapper;

import org.gkd.springwebgkd.bean.WhsSupplyScanx;
import org.gkd.springwebgkd.bean.jpa.WhsSupplyScanxEntity;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class WhsSupplyScanxServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public WhsSupplyScanxServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'WhsSupplyScanxEntity' to 'WhsSupplyScanx'
	 * @param whsSupplyScanxEntity
	 */
	public WhsSupplyScanx mapWhsSupplyScanxEntityToWhsSupplyScan(WhsSupplyScanxEntity whsSupplyScanxEntity) {
		if(whsSupplyScanxEntity == null) {
			return null;
		}

		//--- Generic mapping 
		WhsSupplyScanx whsSupplyScanx = map(whsSupplyScanxEntity, WhsSupplyScanx.class);

		return whsSupplyScanx;
	}
	
	/**
	 * Mapping from 'WhsSupplyScanx' to 'WhsSupplyScanxEntity'
	 * @param whsSupplyScanx
	 * @param whsSupplyScanxEntity
	 */
	public void mapWhsSupplyScanToWhsSupplyScanxEntity(WhsSupplyScanx whsSupplyScanx, WhsSupplyScanxEntity whsSupplyScanxEntity) {
		if(whsSupplyScanx == null) {
			return;
		}

		//--- Generic mapping 
		map(whsSupplyScanx, whsSupplyScanxEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}