/*
 * Created on 19 Jan 2016 ( Time 16:37:22 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.gkd.springwebgkd.service.mapper;

import org.gkd.springwebgkd.bean.WhsStoScan;
import org.gkd.springwebgkd.bean.jpa.WhsStoScanEntity;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class WhsStoScanServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public WhsStoScanServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'WhsStoScanEntity' to 'WhsStoScan'
	 * @param whsStoScanEntity
	 */
	public WhsStoScan mapWhsStoScanEntityToWhsStoScan(WhsStoScanEntity whsStoScanEntity) {
		if(whsStoScanEntity == null) {
			return null;
		}

		//--- Generic mapping 
		WhsStoScan whsStoScan = map(whsStoScanEntity, WhsStoScan.class);

		return whsStoScan;
	}
	
	/**
	 * Mapping from 'WhsStoScan' to 'WhsStoScanEntity'
	 * @param whsStoScan
	 * @param whsStoScanEntity
	 */
	public void mapWhsStoScanToWhsStoScanEntity(WhsStoScan whsStoScan, WhsStoScanEntity whsStoScanEntity) {
		if(whsStoScan == null) {
			return;
		}

		//--- Generic mapping 
		map(whsStoScan, whsStoScanEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}