/*
 * Created on 13 Jan 2016 ( Time 16:21:05 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.gkd.springwebgkd.service;

import java.util.List;
import java.util.Map;

import org.gkd.springwebgkd.bean.MwhsGudang;


/**
 * Business Service Interface for entity MwhsGudang.
 */
public interface MwhsGudangService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param kode
	 * @return entity
	 */
	MwhsGudang findById( String kode  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<MwhsGudang> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	MwhsGudang save(MwhsGudang entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	MwhsGudang update(MwhsGudang entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	MwhsGudang create(MwhsGudang entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param kode
	 */
	void delete( MwhsGudang mwhsGudang, String kode );
	
	List<MwhsGudang> search(Map<String, Object> params);

	String getKodeSite(String npk);
}
