/*
 * Created on 19 Jan 2016 ( Time 16:37:39 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.gkd.springwebgkd.service;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.gkd.springwebgkd.bean.WhsStoScan;
import org.gkd.springwebgkd.bean.WhsSupplyScan;

/**
 * Business Service Interface for entity WhsStoScan.
 */
public interface WhsStoScanService {

	/**
	 * Loads an entity from the database using its Primary Key
	 * 
	 * @param kdTrx
	 * @return entity
	 */
	WhsStoScan findById(BigDecimal kdTrx);

	/**
	 * Loads all entities.
	 * 
	 * @return all entities
	 */
	List<WhsStoScan> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * 
	 * @param entity
	 * @return entity
	 */
	WhsStoScan save(WhsStoScan entity);

	/**
	 * Updates the given entity in the database
	 * 
	 * @param entity
	 * @return
	 */
	WhsStoScan update(WhsStoScan entity);

	/**
	 * Creates the given entity in the database
	 * 
	 * @param entity
	 * @return
	 */
	WhsStoScan create(WhsStoScan entity);

	/**
	 * Deletes an entity using its Primary Key
	 * 
	 * @param kdTrx
	 */
	void delete(WhsStoScan whsStoScan, BigDecimal kdTrx);

	List<WhsStoScan> search(Map<String, Object> params);

	BigDecimal getMaxId();

	String openPeriodeSto();

}
