/*
 * Created on 23 Des 2015 ( Time 11:12:13 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.gkd.springwebgkd.service;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.gkd.springwebgkd.bean.WhsSupplyScan;

/**
 * Business Service Interface for entity WhsSupplyScan.
 */
public interface WhsSupplyScanService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param kdTrx
	 * @return entity
	 */
	WhsSupplyScan findById( BigDecimal kdTrx  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<WhsSupplyScan> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	WhsSupplyScan save(WhsSupplyScan entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	WhsSupplyScan update(WhsSupplyScan entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	WhsSupplyScan create(WhsSupplyScan entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param kdTrx
	 */
	void delete(WhsSupplyScan entity, BigDecimal kdTrx );


	BigDecimal getMaxId();
	
	String openPeriodeLpb();
	
	String openPeriodeBpb();
	
	List<WhsSupplyScan> findListSupplyHarian(String kdGudang);
	
	List<WhsSupplyScan> search(Map<String, Object> params, int maxResult);
	
	BigDecimal findQtySupply(String noBarcode, String bulan, String tahun);
}
