/*
 * Created on 26 Jan 2016 ( Time 08:40:59 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.gkd.springwebgkd.service;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.gkd.springwebgkd.bean.WhsSjScan;


/**
 * Business Service Interface for entity WhsSjScan.
 */
public interface WhsSjScanService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param kdTrx
	 * @return entity
	 */
	WhsSjScan findById( BigDecimal kdTrx  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<WhsSjScan> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	WhsSjScan save(WhsSjScan entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	WhsSjScan update(WhsSjScan entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	WhsSjScan create(WhsSjScan entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param kdTrx
	 */
	void delete(WhsSjScan whsSjScan, BigDecimal kdTrx );

	List<WhsSjScan> search(Map<String, Object> params);

	BigDecimal getMaxId();

	String openPeriodeBpb();

}
